version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: ledger-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ledger_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: ledger-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: ledger_db

volumes:
  mysql_data:
